DataPreparation

In [6]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
Data = pd.read_excel(r"C:\Users\Yamin Hossain\Downloads\crop yeild data sheet - Copy.xlsx")
print(Data)

    Rain Fall (mm)  Fertilizer  Temperatue  Nitrogen (N)  Phosphorus (P)  \
0             1230          80          28            80              24   
1              480          60          36            70              20   
2             1250          75          29            78              22   
3              450          65          35            70              19   
4             1200          80          27            79              22   
..             ...         ...         ...           ...             ...   
94            1250          77          28            78              23   
95             425          60          39            65              19   
96            1220          79          28            77              23   
97             480          65          36            68              21   
98            1230          80          28            80              24   

    Potassium (K)  Yeild (Q/acre)  
0              20            12.0  
1              

In [26]:
x = Data.iloc[:,[2,3]].values
y = Data.iloc[:,4].values

In [28]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.7, random_state=42)
x_train.shape, x_test.shape

((29, 2), (70, 2))

In [31]:
from sklearn.preprocessing import StandardScaler
st_x = StandardScaler()
x_train = st_x.fit_transform(x_train)
x_test = st_x.transform(x_test)

In [38]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(random_state=42, n_jobs=-1,  max_depth=5,n_estimators=100,oob_score=True)
classifier.fit(x_train,y_train)
classifier.oob_score_

0.3448275862068966

In [34]:
y_pred = classifier.predict(x_test)
print(y_pred)

[21 23 19 22 22 23 24 22 21 21 18 21 22 18 24 21 19 21 23 20 19 24 21 18
 19 19 18 20 19 22 21 24 21 18 22 20 19 19 21 21 23 22 19 21 21 22 22 19
 19 19 20 19 24 21 18 23 19 22 18 22 21 21 19 22 24 24 19 20 23 22]


In [37]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
cm2 = classification_report(y_test,y_pred)
print(cm2)
cm3 = accuracy_score(y_test,y_pred)
print(cm3)

[[5 5 0 0 1 0 0]
 [1 5 1 0 0 0 0]
 [1 2 3 0 1 0 0]
 [0 3 1 2 1 1 2]
 [0 1 0 2 7 1 2]
 [0 0 0 6 2 4 2]
 [0 0 0 6 1 0 1]]
              precision    recall  f1-score   support

          18       0.71      0.45      0.56        11
          19       0.31      0.71      0.43         7
          20       0.60      0.43      0.50         7
          21       0.12      0.20      0.15        10
          22       0.54      0.54      0.54        13
          23       0.67      0.29      0.40        14
          24       0.14      0.12      0.13         8

    accuracy                           0.39        70
   macro avg       0.44      0.39      0.39        70
weighted avg       0.47      0.39      0.40        70

0.38571428571428573
